on:
  schedule:
  - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Retrieve
      run: |
        for repository in gpu-py3-cloud-runner gpu-cloud-runner py3-cloud-runner cloud-runner; do
          curl -L "https://hub.docker.com/v2/repositories/dvcorg/cml-$repository" \
          | jq .pull_count | paste <(date +%s) - >> "cml-$repository"
        done
    - name: Commit
      run: |
        git config --local user.name "Olivaw[bot]"
        git config --local user.email "64868532+Olivaw[bot]@users.noreply.github.com"
        git commit -am cron
        git push
