on:
  schedule:
  - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Retrieve
      run: >-
        for repository in
        
        cml-gpu-py3-cloud-runner
        cml-gpu-cloud-runner
        cml-py3-cloud-runner
        cml-cloud-runner;
        
        do
        
        curl --location "https://hub.docker.com/v2/repositories/dvcorg/$repository"
        | jq .pull_count
        | paste <(date +%s) -
        >> "$repository";
        
        done
    - name: Commit
      run: |
        git config --local user.name "Olivaw[bot]"
        git config --local user.email "64868532+Olivaw[bot]@users.noreply.github.com"
        git commit -am cron
        git push
